### ISSUE TITLE
Kerishnie Digital PhotoBook

### ISSUE THREAD

**Issue by fsn-mandy** [FsN/FsN_Internal#13]
@Annette-FSN 

phase 1editing. phase 2 layout. phase 3adding annotations 
**phase 1 Photo editing** deadline was 11th month 
due completion all ready for printing by June 30 for printing 15 July 
leaving 2 weeks for printing and 5 days for delivery and client pushed the entire project to 15 July for phase 1 thus pushing phase 2 and 3 out past the deadline for printing 

- the project was completed 22 June it just need the quotes to do stage 3
- editing was done, layout was done  
- client wanted changes on the layout and to add more pictures pushing out the deadline from 13 June
- so not everything can fit now we have to relay out so the project was done but it has pushed out the deadline as the client wants to add more pictures and started the project back to zero in terms of the layout 

**phase 2 layout** deadline was june week 
12 hours
- 1300 photos edited handed back to Kerishnie to reduce  the number images to 900 24 June
- Kerishnie to upload pictures the storage cloud or deliver the drive to Byron or collect it 29 June
- pictures get edited with text on the page on the image therefore all images need to be set on layout
- this deadline is 30 June

**phase 3 quotes and annotations on pages**  June week 3
200 pages x 30 min will take 25 days additional days this must be done by the client with training
- editing of pages with wording and quotes to be done by client

**Comment by byron-fsintel** [comment]
Phase 1 Photo editing was completed before commencement of work for FSN.
Phase 2 layout was completed however software limitations did not work with the amount of images.
Kerishnie has been informed that the 30th June is the cutoff date for this project. All materials will be handed over to her, she contacted a printing press professional named Johnathan who has advised her to get the edited images, additional layout tasks is not possible due to time constraints. The cut down image folder is in Kershnies possession. Scans and additional images will be collected by her.
Phase 3 quotes and annotations could not be completed before layout was, this is the time consuming part as K would of liked to sit down and annotate all 200 pages with me. Had instructions been delivered the process would take 5 minutes per page. 5 x 200 = Approx 17 hours. Without knowing where the quotes should be implemented this can take much longer pushing project far past deadlines.
